language: node_js
node_js:
- 6
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e8f4194820c6_key -iv $encrypted_e8f4194820c6_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'xcatliu'
- git config --global user.email 'xcatliu@gmail.com'
script:
- bash ./bin/deploy-gh-pages.sh
- git remote add coding git@git.coding.net:xcatliu/from-javascript-to-typescript.git
- git push coding master
- bash ./bin/deploy-coding-pages.sh
